name: deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
      - name: Deploy
        uses: dagger/dagger-for-github@8.0.0
        with:
          verb: call
          args: deploy --registry-password=env://GH_API_KEY --kubectl-file=env://KUBECTL_FILE
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "0.19.11"
        env:
          GH_API_KEY: ${{ secrets.GH_API_KEY }}
          KUBECTL_FILE: ${{ secrets.KUBECTL_FILE }}

permissions:
  id-token: write
